<?php

/**
 * @file
 * Defines a field type to embed views in an entity reference field.
 */

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function viewsreference_help($route_name, RouteMatchInterface $arg) {
  if ($route_name === 'help.page.viewsreference') {
    $output = file_get_contents(drupal_get_path('module', 'viewsreference') . '/README.md');
    return \Drupal::moduleHandler()->moduleExists('markdown') ? \Drupal\Component\Utility\Xss::filterAdmin(\Drupal::moduleHandler()->invoke('markdown', 'filter', ['process', 0, -1, $output])) : '<h3>viewsreference README</h3><pre>' . \Drupal\Component\Utility\Html::escape($output) . '</pre>';
  }
}

/**
 * Implements hook_theme().
 */
function viewsreference_theme($existing, $type, $theme, $path) {
  return [
    'viewsreference__view_title' => [
      'template' => 'viewsreference--view-title',
      'render element' => 'variables',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function viewsreference_preprocess_viewsreference__view_title(&$variables) {
  $variables['title'] = ['#markup' => $variables['variables']['#title']];
}
