sudo: false
language: php
dist: trusty

php:
  - 7.1

matrix:
  fast_finish: true

env:
  global:
    - DEPLOY_SOURCE_BRANCH=8.x
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR
    - IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    - BUILD_DIR=$TRAVIS_BUILD_DIR

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.console"
  - "$HOME/.drush/cache"
  - "$HOME/.nvm"

addons:
  chrome: stable

before_install:
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install

script:
    - php core/scripts/run-tests.sh --sqlite /tmp/.ht.sqlite --die-on-fail --dburl sqlite://tmp/.ht.sqlite --all
    - test.sh
