name: Charts API Example
type: module
description: Demonstrates how to use the Charts module without Views.
# core: 8.x
package: Examples
dependencies:
  - charts:charts

# Information added by Drupal.org packaging script on 2017-09-19
version: '8.x-3.0-alpha6'
core: '8.x'
project: 'charts'
datestamp: 1505801647
